name: desktop
description: Flutter design standard for desktop. Just simple, usable wigdets to create apps. See the galery for examples of the components used.
repository: https://github.com/adrianos42/desktop
homepage: https://adrianos42.github.io/desktop
version: 3.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
